# TensorFlow程序设计模式介绍

TensorFlow程序设计模式的核心是"计算图"，可分为两部分：建立“计算图”与执行“计算图”。

使用TensorFlow提供的模块建立“计算图”。TensorFlow提供的模块非常强大，可以设计张量运算流程，并且构建各种深度学习或机器学习模型。

建立“计算图”后，需要建立Session执行“计算图”。在TensorFlow中，Session的作用是在客户端和执行设备之间建立连接。有了这个连接，就可以将“计算图”在各种不同的设备中执行，后续任何与设备之间的数据传输都必须通过Session才能进行，执行“计算图”后会返回结果。

## 1 建立计算图

建立一个简单的“计算图”，只有一个常数与一个变量。建立完成后再执行此“计算图”。

In [18]:
#导入TensorFlow模块
import tensorflow as tf

In [19]:
#建立TensorFlow常数
ts_c = tf.constant(2,name='ts_c') #设置常数值为2，名称为ts_c

In [20]:
ts_c

<tf.Tensor 'ts_c_1:0' shape=() dtype=int32>

tf.Tensor代表这是TensorFlow张量；shape()代表这是零维的tensor,也就是数值；dtype=int32代表张量数据类型是int32。

In [21]:
#建立TensorFlow变量
ts_x = tf.Variable(ts_c+5,name='ts_x')

In [22]:
ts_x

<tf.Variable 'ts_x_1:0' shape=() dtype=int32_ref>

## 2 执行计算图

In [23]:
#建立计算图
sess= tf.Session()

In [24]:
#执行TensorFlow初始化变量
init = tf.global_variables_initializer()
sess.run(init)

In [25]:
#使用sess.run显示TensorFlow常数
print('ts_c=',sess.run(ts_c))

ts_c= 2


In [26]:
#使用sess.run显示TensorFlow变量
print('ts_x=',sess.run(ts_x))

ts_x= 7


另一个执行TensorFlow“计算图”的方法是使用TensorFlow对象的eval()方法，使用此方法必须传入session参数。

In [27]:
#使用.eval()方法显示TensorFlow常数
print('ts_c=',ts_c.eval(session=sess))

ts_c= 2


In [28]:
#使用.eval()方法显示TensorFlow变量
print('ts_x=',ts_x.eval(session=sess))

ts_x= 7


In [29]:
#关闭Session
sess.close()

当使用tf.Session()建立Session,并使用sess.close()关闭Session时。可能会忘记关闭Session或者程序异常时也会导致没有关闭Session。为解决以上问题，可以使用With语句：

In [30]:
a = tf.constant(2,name='a')
x = tf.Variable(a+5,name='x')
with tf.Session() as sess:
    init=tf.global_variables_initializer()
    sess.run(init)
    print('a=',sess.run(a))
    print('x=',sess.run(x))

a= 2
x= 7


在with程序块中可使用sess变量与设备沟通，离开with程序块就自动关闭Session。

## 3 TensorFlow placeholder

如果希望在执行“计算图”阶段才设置数值，那么必须使用placeholder。

以下建立两个placeholder（占位符）,分别是width（宽）与height（高），然后使用tf.multiply将width与heigh相乘，相乘后的结果是area（面积）。

In [31]:
#建立计算图
width = tf.placeholder("int32",name='width')         #name参数设置的名称会显示在TensorBoard Graph中
height = tf.placeholder("int32",name='height')
area = tf.multiply(width,height,name='area')

In [32]:
#执行计算图
#执行sess.run传入feed_dict参数｛width:6,height:8｝
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=',sess.run(area,feed_dict={width:6,height:8}))

area= 48


## 4 TensorFlow数值运算方法介绍

TensorFlow提供了很多数值运算，Tensorflow说明文件的网址为：http://www.tensorfly.cn/tfdoc/api_docs/python/math_ops.html

简单的数值相乘，为什么要使用tf.multiply()?

因为TensorFlow特别的程序设计模式必须以TensorFlow模块（例如tf.multiply()方法）来建立“计算图”，然后使用sess.run执行“计算图”，这样才能得到计算的结果。这样做的目的是让TensorFlow具备跨平台的能力。

## 5 TensorBoard

TensorFlow提供的TensorBoard，可以以可视化的方式显示所建立的“计算图”。

In [33]:
#将要显示在TensorBoard的数据写入log文件
tf.summary.merge_all()                     #将所有要显示在TensorBoard的数据整合
train_writer = tf.summary.FileWriter('log/area',sess.graph) #将所有要显示在TensorBoard的数据写入log文件。 

确认log目录文件已经产生：dir e:\pythonwork\log\area

进入工作目录，启动TesorFlow的Anaconda虚拟环境：activate tensorFlow

启动TensorBoard: tensorboard --logdir=e:\pythonwork\log\area

查看计算图：在浏览器中输入http://localhost:6006

## 6 建立一维与二维张量

之前介绍了零维的张量，也就是标量（数值）。TensorFlow还可以建立一维的张量（向量）与二维以上的张量（矩阵）

In [36]:
#建立一维张量
ts_1=tf.Variable([0.4,0.2,0.4])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_1)
    print(X)

[0.4 0.2 0.4]


In [37]:
#查看一维张量
print(X.shape)   #一维张量共有3个数值，所以显示（3，）

(3,)


In [38]:
#建立二维张量
ts_2=tf.Variable([[0.4,0.2,0.4]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_2)
    print(X)

[[0.4 0.2 0.4]]


In [39]:
print(X.shape)

(1, 3)


In [41]:
W = tf.Variable([[-0.5,-0.2],
                 [-0.3,0.4],
                 [-0.5,0.2]])
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_array = sess.run(W)
    print(W_array)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]


In [42]:
print(W_array.shape)

(3, 2)


## 7 矩阵基本运算

In [45]:
#矩阵的乘法与加法
X = tf.Variable([[1.,1.,1.]])         #此处为浮点数

W = tf.Variable([[-0.5,-0.2],
                 [-0.3,0.4],
                 [-0.5,0.2]])

b = tf.Variable([[0.1,0.2]])

XWb = tf.matmul(X,W)+b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:')
    print(sess.run(XWb))

XWb:
[[-1.1999999  0.6      ]]
